name: Node.js CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.14.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo 'export BUN_INSTALL="$HOME/.bun"' >> ~/.bashrc
        echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> ~/.bashrc

    - name: Load Bun environment variables
      run: |
        echo 'BUN_INSTALL=$HOME/.bun' >> ~/.bashrc
        echo 'PATH=$BUN_INSTALL/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc

    - name: Install dependencies
      run: |
        source ~/.bashrc
        bun install

    - name: Run tests
      run: |
        source ~/.bashrc
        bun test

    - name: Build project
      run: |
        source ~/.bashrc
        bun run build
